# Cursor style
[cursor.style]
shape = "block"

# Font settings
[font]
size = 10

[font.bold]
family = "FiraCodeNerdFontMono"
style = "Bold"

[font.italic]
family = "FiraCodeNerdFontMono" 
style = "Italic"

[font.normal]
family = "FiraCodeNerdFontMono"
style = "Regular"

# Window settings
[window]
opacity = 0.9


# GruvBox Color Scheme

[colors]
[colors.primary]
background = "#282828"  # Dark background
foreground = "#ebdbb2"  # Light foreground (text)

[colors.cursor]
text = "#282828"
cursor = "#ebdbb2"

[colors.normal]
black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"
